provider:
  name: openfaas
  gateway: http://127.0.0.1:31112

functions:
  # dashboard
  faas-flow-dashboard:
    lang: Dockerfile
    handler: ./dashboard
    image: s8sg/faas-flow-dashboard:3.0.3
    environment:
      write_debug: true
      combine_output: false
    environment_file:
      - conf.yml
    secrets:
      - basic-auth
    labels:
      com.openfaas.scale.zero: "false"

  # list flow functions deployed in openfaas
  list-flow-functions:
    lang: go
    handler: ./list-flow-functions
    image: s8sg/list-flow-functions:1.0.1
    environment:
      write_debug: true
      combine_output: false
    environment_file:
      - conf.yml
    secrets:
      - basic-auth
    labels:
      com.openfaas.scale.zero: "false"

  # Generate dot graph for faas-flow
  dot-generator:
    lang: go
    handler: ./dot-generator
    image: s8sg/dot-generator:1.2.0
    environment_file:
      - conf.yml
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
    labels:
      com.openfaas.scale.zero: "false"

  # Collect metrics for faas-flow
  metrics:
    lang: go
    handler: ./metrics
    image: s8sg/metrics:1.6.0
    environment_file:
      - conf.yml
    environment:
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
    labels:
      com.openfaas.scale.zero: "false"
